# Generated by Django 4.0.5 on 2022-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_customuser_avatar_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='technology',
            field=models.ManyToManyField(related_name='users', to='profiles.technology'),
        ),
    ]
